version: '3'
services:

  ledger:
    image: trufflesuite/ganache-cli:latest
    hostname: ledger
    ports:
      - "8545:8545"
    command: ganache-cli --port=8545 --defaultBalanceEther=10 --blockTime=1 --account='${TEST_PRIVATE_KEY},500000000000000000000' --unlock='${TEST_ADDRESS}'

  cite:
    build:
      context: ./src/
      dockerfile: SubDockerfile
    hostname: cite
    depends_on:
      - ledger
